name: Construir Conector AeroHub
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install and Build
        shell: bash
        run: |
          # Este comando procura a pasta onde está o package.json e entra nela
          target_dir=$(find . -name package.json -not -path "*/node_modules/*" -exec dirname {} \;)
          cd "$target_dir"
          npm install
          npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: "**/*.exe" # Procura o instalador em qualquer pasta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
